# Generated by Django 6.0.3 on 2026-03-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField(default='')),
                ('cover', models.ImageField(default='covers/default.jpg', upload_to='covers/')),
                ('source', models.URLField()),
                ('clean_source', models.URLField(blank=True, null=True)),
                ('languages', models.CharField(choices=[('tr', 'Turkish'), ('en', 'English'), ('es', 'Spanish'), ('ar', 'Arabic')], max_length=2)),
                ('subtitles', models.CharField(blank=True, choices=[('tr', 'Turkish'), ('en', 'English'), ('es', 'Spanish'), ('ar', 'Arabic')], max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('publish', models.DateTimeField(blank=True, null=True)),
                ('draft', models.BooleanField(default=True)),
            ],
        ),
    ]
